In [ ]:
# Nama Lengkap: Khairil Ramadhani
# NIM: 240401040511
# Kelas: IF405

In [ ]:
# Install mlxtend jika belum tersedia di environment
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.12/dist-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.0.2)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2026.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)

In [ ]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

# Membuat dataset transaksi ritel sederhana (Market Basket Analysis)
data = {
    'Roti': [1, 1, 0, 1, 1, 0],
    'Susu': [1, 1, 1, 0, 1, 1],
    'Kopi': [0, 1, 1, 1, 0, 1],
    'Gula': [0, 0, 1, 1, 0, 1],
    'Teh': [1, 0, 0, 1, 1, 0]
}
df = pd.DataFrame(data)

print("--- DataFrame Transaksi ---")
display(df)

# Mencari Frequent Itemsets menggunakan Algoritma Apriori
frequent_itemsets = apriori(df, min_support=0.3, use_colnames=True)
print("\n--- Frequent Itemsets ---")
display(frequent_itemsets)

# Membuat Association Rules berdasarkan Confidence
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6)
print("\n--- Association Rules ---")
display(rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']])

--- DataFrame Transaksi ---

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

   Roti  Susu  Kopi  Gula  Teh
0     1     1     0     0    1
1     1     1     1     0    0
2     0     1     1     1    0
3     1     0     1     1    1
4     1     1     0     0    1
5     0     1     1     1    0

--- Frequent Itemsets ---

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/mlxtend/frequent_patterns/fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

     support            itemsets
0   0.666667              (Roti)
1   0.833333              (Susu)
2   0.666667              (Kopi)
3   0.500000              (Gula)
4   0.500000               (Teh)
5   0.500000        (Roti, Susu)
6   0.333333        (Roti, Kopi)
7   0.500000         (Roti, Teh)
8   0.500000        (Susu, Kopi)
9   0.333333        (Susu, Gula)
10  0.333333         (Susu, Teh)
11  0.500000        (Kopi, Gula)
12  0.333333   (Roti, Susu, Teh)
13  0.333333  (Susu, Kopi, Gula)

--- Association Rules ---

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

     antecedents   consequents   support  confidence      lift
0         (Roti)        (Susu)  0.500000    0.750000  0.900000
1         (Susu)        (Roti)  0.500000    0.600000  0.900000
2         (Roti)         (Teh)  0.500000    0.750000  1.500000
3          (Teh)        (Roti)  0.500000    1.000000  1.500000
4         (Susu)        (Kopi)  0.500000    0.600000  0.900000
5         (Kopi)        (Susu)  0.500000    0.750000  0.900000
6         (Gula)        (Susu)  0.333333    0.666667  0.800000
7          (Teh)        (Susu)  0.333333    0.666667  0.800000
8         (Kopi)        (Gula)  0.500000    0.750000  1.500000
9         (Gula)        (Kopi)  0.500000    1.000000  1.500000
10  (Roti, Susu)         (Teh)  0.333333    0.666667  1.333333
11   (Roti, Teh)        (Susu)  0.333333    0.666667  0.800000
12   (Susu, Teh)        (Roti)  0.333333    1.000000  1.500000
13         (Teh)  (Roti, Susu)  0.333333    0.666667  1.333333
14  (Susu, Kopi)        (Gula)  0.333333    0.666667  1.333333
15  (Susu, Gula)        (Kopi)  0.333333    1.000000  1.500000
16  (Kopi, Gula)        (Susu)  0.333333    0.666667  0.800000
17        (Gula)  (Susu, Kopi)  0.333333    0.666667  1.333333

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

### Kesimpulan
- **Apa yang dipelajari:** Memahami konsep *Association Rule Mining* menggunakan Algoritma Apriori (*Market Basket Analysis*) untuk mencari pola kebiasaan pembelian barang dengan parameter *Support*, *Confidence*, dan *Lift*, serta pengantar sistem rekomendasi dasar.
- **Temuan utama:** Nilai *Lift* > 1 menunjukkan adanya hubungan asosiasi yang kuat dan bermakna antar item produk yang sering dibeli secara bersamaan oleh konsumen.
- **Keterbatasan / Pertanyaan:** Proses pencarian aturan asosiasi dapat menjadi lambat (*combinatorial explosion*) apabila jumlah variasi produk dan transaksi data ritel berukuran sangat besar.